config/routes.rb
GmapEvents::Application.routes.draw do
  resources :events, :maps

  root :to => "maps#index"
  

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/map.rb
class Map < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:event_name, :event_start_date, :event_start_time, :event_end_date, :event_end_time, :event_desc, :text, :map_id, :integer)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render action: 'show', status: :created, location: @map }
      else
        format.html { render action: 'new' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:latitude, :longitude, :name, :formatted_address, :formatted_phone_number, :rating, :url, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_name %><br>
    <%= f.text_field :event_name %>
  </div>
  <div class="field">
    <%= f.label :event_start_date %><br>
    <%= f.date_select :event_start_date %>
  </div>
  <div class="field">
    <%= f.label :event_start_time %><br>
    <%= f.time_select :event_start_time %>
  </div>
  <div class="field">
    <%= f.label :event_end_date %><br>
    <%= f.date_select :event_end_date %>
  </div>
  <div class="field">
    <%= f.label :event_end_time %><br>
    <%= f.time_select :event_end_time %>
  </div>
  <div class="field">
    <%= f.label :event_desc %><br>
    <%= f.text_field :event_desc %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :map_id %><br>
    <%= f.text_field :map_id %>
  </div>
  <div class="field">
    <%= f.label :integer %><br>
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event start date</th>
      <th>Event start time</th>
      <th>Event end date</th>
      <th>Event end time</th>
      <th>Event desc</th>
      <th>Text</th>
      <th>Map</th>
      <th>Integer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.event_name %></td>
        <td><%= event.event_start_date %></td>
        <td><%= event.event_start_time %></td>
        <td><%= event.event_end_date %></td>
        <td><%= event.event_end_time %></td>
        <td><%= event.event_desc %></td>
        <td><%= event.text %></td>
        <td><%= event.map_id %></td>
        <td><%= event.integer %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @event.event_name %>
</p>

<p>
  <strong>Event start date:</strong>
  <%= @event.event_start_date %>
</p>

<p>
  <strong>Event start time:</strong>
  <%= @event.event_start_time %>
</p>

<p>
  <strong>Event end date:</strong>
  <%= @event.event_end_date %>
</p>

<p>
  <strong>Event end time:</strong>
  <%= @event.event_end_time %>
</p>

<p>
  <strong>Event desc:</strong>
  <%= @event.event_desc %>
</p>

<p>
  <strong>Text:</strong>
  <%= @event.text %>
</p>

<p>
  <strong>Map:</strong>
  <%= @event.map_id %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @event.integer %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GmapEvents</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>   
  <% end %>

  <div class="field">
    <input id="map_location" placeholder="Enter Place or Address" type="text"></input>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field(:latitude, :id => "latitude" ) %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field(:longitude, :id => "longitude") %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field(:name, :id => "name") %>
  </div>
  <div class="field">
    <%= f.label :formatted_address %><br>
    <%= f.text_field(:formatted_address, :id => "formatted_address") %>
  </div>
  <div class="field">
    <%= f.label :formatted_phone_number %><br>
    <%= f.text_field(:formatted_phone_number, :id => "formatted_phone_number")%>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_field(:rating, :id => "rating") %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field(:url, :id => "url")%>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field(:website, :id => "website")%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing map</h1>

<%= render 'form' %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">

<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry,places,panoramio" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script type="text/javascript" src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/routeboxer/src/RouteBoxer.js"></script>

<%= javascript_tag do %>
  window.maps = <%= raw Map.all.to_json %>  
<% end %>

<div id="screenDIV">
  <table>
      <tr>
        <td style="width: 31%;" align="left" valign="top">
          <div class="btnDIV">
            <%= link_to "New Location", new_map_path, :class=>"btn btn-primary btn-sm", :id => "newloc" %>
          </div>
          <% iMarker = "A" %>  
          <ul class="mapSidebar" id="markers_list">
              <% @maps.each do |map| %>
                  <li>
                    <ol>
                        <li><img src= "http://maps.google.com/mapfiles/kml/paddle/<%= iMarker %>.png" class="markerSize" />&nbsp;<a href="javascript:void(0);" class="mapEventName"><%= map.name %></a></li>
                        <li>
                            <ul>
                                <li class="mapEventLocation"><%= map.name %></li>
                                <li class="mapEventLocation"><%= map.formatted_address %></li>
                                <li></li>
                                <li class="mapEditDelete"><%= link_to 'Delete', map, method: :delete, data: { confirm: 'Do you want to remove the location ' + map.name + '?' } %></li>
                            </ul>
                        </li>
                    </ol>
                  </li>    
                  <% iMarker = iMarker.succ %>
                  <br />
              <% end %>
          </ul>   
        </td>
        <td style="width: 1%"></td>         
        <td class="mapSection">
            <div id="map" class="mapDIV"></div>
            <div id="modeDIV">
              <select id="mode">
                <option value="DRIVING">Driving</option>
                <option value="WALKING">Walking</option>
                <option value="BICYCLING">Bicycling</option>
                <option value="TRANSIT">Transit</option>
              </select>
            </div>    
            <div id="panoDIV"></div>        
        </td>
      </tr>
  </table>
</div>

<!-- <div id="mylocDIV">
  <= link_to "On", maps_path, :class=>"btn btn-primary btn-xs", :rel =>"my location is ON", :id => "myloc" %>
</div> -->
<div class="modal fade" id="directions-panel">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h4 id="RouteDirTitle">Route Direction</h4>
  </div>
  <div class="modal-body" id="directionDetail">
    <p></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">Close</a>
  </div>
</div>    

app/views/maps/index_3.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Directly accessing Street View data</title>
    <style>
      html, body, #map {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
    <script>
var map;
var berkeley = new google.maps.LatLng(37.869085,-122.254775);
var sv = new google.maps.StreetViewService();

var panorama;

function initialize() {

  panorama = new google.maps.StreetViewPanorama(document.getElementById('pano'));

  // Set up the map
  var mapOptions = {
    center: berkeley,
    zoom: 16,
    streetViewControl: false
  };
  map = new google.maps.Map(document.getElementById('map'),
      mapOptions);

  // getPanoramaByLocation will return the nearest pano when the
  // given radius is 50 meters or less.
  google.maps.event.addListener(map, 'click', function(event) {
      sv.getPanoramaByLocation(event.latLng, 50, processSVData);
  });
}

function processSVData(data, status) {
  if (status == google.maps.StreetViewStatus.OK) {
    var marker = new google.maps.Marker({
      position: data.location.latLng,
      map: map,
      title: data.location.description
    });

    panorama.setPano(data.location.pano);
    panorama.setPov({
      heading: 270,
      pitch: 0
    });
    panorama.setVisible(true);

    google.maps.event.addListener(marker, 'click', function() {

      var markerPanoID = data.location.pano;
      // Set the Pano to use the passed panoID
      panorama.setPano(markerPanoID);
      panorama.setPov({
        heading: 270,
        pitch: 0
      });
      panorama.setVisible(true);
    });
  } else {
    alert('Street View data not found for this location.');
  }
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  </head>
  <body>
    <div id="map" style="width: 45%; height: 100%;float:left"></div>
    <div id="pano" style="width: 45%; height: 100%;float:left"></div>
  </body>
</html>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @map.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @map.longitude %>
</p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<p>
  <strong>Formatted address:</strong>
  <%= @map.formatted_address %>
</p>

<p>
  <strong>Formatted phone number:</strong>
  <%= @map.formatted_phone_number %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @map.rating %>
</p>

<p>
  <strong>Url:</strong>
  <%= @map.url %>
</p>

<p>
  <strong>Website:</strong>
  <%= @map.website %>
</p>

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>